# Generated by Django 6.1 on 2026-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Título')),
                ('author', models.CharField(max_length=100, verbose_name='Autor')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/', verbose_name='Portada')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price', models.IntegerField(verbose_name='Precio ($CLP)')),
            ],
            options={
                'verbose_name': 'Libro',
                'verbose_name_plural': 'Cargos',
                'db_table': 'books',
                'ordering': ['title'],
            },
        ),
    ]
