# Generated by Django 6.1 on 2026-09-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Álbum')),
                ('artist', models.CharField(max_length=100, verbose_name='Artista')),
                ('year', models.IntegerField(verbose_name='Año')),
                ('genre', models.CharField(max_length=100, verbose_name='Género')),
                ('image', models.ImageField(blank=True, null=True, upload_to='music/', verbose_name='Caratula')),
                ('stock', models.IntegerField(default=0, verbose_name='Stock')),
                ('price', models.IntegerField(verbose_name='Precio ($)')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albumes',
                'db_table': 'music',
                'ordering': ['title'],
            },
        ),
    ]
