# Generated by Django 6.1 on 2026-09-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_catalog', '0002_alter_album_image_alter_album_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='price',
            field=models.IntegerField(verbose_name='Precio ($CLP)'),
        ),
    ]
