# Generated by Django 6.1 on 2026-09-27 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_catalog', '0003_alter_album_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Artista')),
            ],
        ),
        migrations.CreateModel(
            name='MusicGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Género Musical')),
            ],
        ),
        migrations.AlterModelOptions(
            name='album',
            options={},
        ),
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Álbum'),
        ),
        migrations.AlterModelTable(
            name='album',
            table=None,
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_catalog.artist', verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_catalog.musicgenre', verbose_name='Género'),
        ),
    ]
