# Generated by Django 6.1 on 2026-09-27 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_catalog', '0004_artist_musicgenre_alter_album_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MusicGenre',
            new_name='Genre',
        ),
    ]
